version: "3.0"

services:
  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
      - "22:22"
    volumes:
      - ./runbooks:/runbooks
      - /home/${USER}/.ssh:/home/jovyan/.ssh
      - /tmp/data:/data
  kibana:
    image: kibana:7.8.0
    container_name: kibana
    ports:
      - "5601:5601"

      