version: "3.0"

services:
  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    #links:
    #  - postgres-db
    volumes:
      - ./runbooks:/runbooks
      - ./.ssh:/home/jovyan/.ssh
      - /tmp/data:/data
      